// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_site

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SiteResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "Numeric identifier of the site",
				MarkdownDescription: "Numeric identifier of the site",
			},
			"title": schema.StringAttribute{
				Required:            true,
				Description:         "Title of the site",
				MarkdownDescription: "Title of the site",
			},
			"url": schema.StringAttribute{
				Required:            true,
				Description:         "URL of the site",
				MarkdownDescription: "URL of the site",
			},
		},
	}
}

type SiteModel struct {
	Id    types.Int64  `tfsdk:"id"`
	Title types.String `tfsdk:"title"`
	Url   types.String `tfsdk:"url"`
}
